# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby_css_lint"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Mutz"]
  s.date = "2012-06-20"
  s.description = "Wraps up the CSS lint tool from https://github.com/stubbornella/csslint into a gem"
  s.email = "andrew.mutz@appfolio.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "csslint/CHANGELOG",
    "csslint/LICENSE",
    "csslint/README.md",
    "csslint/build.xml",
    "csslint/demos/CSSLintDemo.htm",
    "csslint/demos/demo.css",
    "csslint/lib/js.jar",
    "csslint/lib/jshint.js",
    "csslint/lib/parserlib.js",
    "csslint/lib/yuitest-rhino-cli.js",
    "csslint/lib/yuitest.js",
    "csslint/npm/package.json",
    "csslint/release/csslint-node.js",
    "csslint/release/csslint-rhino.js",
    "csslint/release/csslint-tests.js",
    "csslint/release/csslint-worker.js",
    "csslint/release/csslint-wsh.js",
    "csslint/release/csslint.js",
    "csslint/release/npm/cli.js",
    "csslint/release/npm/lib/csslint-node.js",
    "csslint/release/npm/package.json",
    "csslint/src/cli/common.js",
    "csslint/src/cli/node.js",
    "csslint/src/cli/rhino.js",
    "csslint/src/cli/wsh.js",
    "csslint/src/core/CSSLint.js",
    "csslint/src/core/Reporter.js",
    "csslint/src/core/Util.js",
    "csslint/src/formatters/checkstyle-xml.js",
    "csslint/src/formatters/compact.js",
    "csslint/src/formatters/csslint-xml.js",
    "csslint/src/formatters/lint-xml.js",
    "csslint/src/formatters/text.js",
    "csslint/src/rules/adjoining-classes.js",
    "csslint/src/rules/box-model.js",
    "csslint/src/rules/box-sizing.js",
    "csslint/src/rules/compatible-vendor-prefixes.js",
    "csslint/src/rules/display-property-grouping.js",
    "csslint/src/rules/duplicate-background-images.js",
    "csslint/src/rules/duplicate-properties.js",
    "csslint/src/rules/empty-rules.js",
    "csslint/src/rules/errors.js",
    "csslint/src/rules/fallback-colors.js",
    "csslint/src/rules/floats.js",
    "csslint/src/rules/font-faces.js",
    "csslint/src/rules/font-sizes.js",
    "csslint/src/rules/gradients.js",
    "csslint/src/rules/ids.js",
    "csslint/src/rules/import.js",
    "csslint/src/rules/important.js",
    "csslint/src/rules/known-properties.js",
    "csslint/src/rules/outline-none.js",
    "csslint/src/rules/overqualified-elements.js",
    "csslint/src/rules/qualified-headings.js",
    "csslint/src/rules/regex-selectors.js",
    "csslint/src/rules/rules-count.js",
    "csslint/src/rules/shorthand.js",
    "csslint/src/rules/star-property-hack.js",
    "csslint/src/rules/text-indent.js",
    "csslint/src/rules/underscore-property-hack.js",
    "csslint/src/rules/unique-headings.js",
    "csslint/src/rules/universal-selector.js",
    "csslint/src/rules/unqualified-attributes.js",
    "csslint/src/rules/vendor-prefix.js",
    "csslint/src/rules/zero-units.js",
    "csslint/src/worker/Worker.js",
    "csslint/tests/all-rules.js",
    "csslint/tests/core/CSSLint.js",
    "csslint/tests/core/Reporter.js",
    "csslint/tests/css/width-100.html",
    "csslint/tests/formatters/checkstyle-xml.js",
    "csslint/tests/formatters/compact.js",
    "csslint/tests/formatters/csslint-xml.js",
    "csslint/tests/formatters/lint-xml.js",
    "csslint/tests/formatters/text.js",
    "csslint/tests/rules/adjoining-classes.js",
    "csslint/tests/rules/box-model.js",
    "csslint/tests/rules/box-sizing.js",
    "csslint/tests/rules/compatible-vendor-prefixes.js",
    "csslint/tests/rules/display-property-grouping.js",
    "csslint/tests/rules/duplicate-background-images.js",
    "csslint/tests/rules/duplicate-properties.js",
    "csslint/tests/rules/empty-rules.js",
    "csslint/tests/rules/errors.js",
    "csslint/tests/rules/fallback-colors.js",
    "csslint/tests/rules/floats.js",
    "csslint/tests/rules/font-faces.js",
    "csslint/tests/rules/font-sizes.js",
    "csslint/tests/rules/gradients.js",
    "csslint/tests/rules/ids.js",
    "csslint/tests/rules/import.js",
    "csslint/tests/rules/important.js",
    "csslint/tests/rules/known-properties.js",
    "csslint/tests/rules/outline-none.js",
    "csslint/tests/rules/overqualified-elements.js",
    "csslint/tests/rules/qualified-headings.js",
    "csslint/tests/rules/regex-selectors.js",
    "csslint/tests/rules/shorthand.js",
    "csslint/tests/rules/star-property-hack.js",
    "csslint/tests/rules/text-indent.js",
    "csslint/tests/rules/underscore-property-hack.js",
    "csslint/tests/rules/unique-headings.js",
    "csslint/tests/rules/universal-selector.js",
    "csslint/tests/rules/unqualified-attributes.js",
    "csslint/tests/rules/vendor-prefix.js",
    "csslint/tests/rules/zero-units.js",
    "csslint/tests/testrunner.htm",
    "js.jar",
    "lib/ruby_css_lint.rb",
    "test/helper.rb",
    "test/test_ruby_css_lint.rb"
  ]
  s.homepage = "http://github.com/amutz/ruby_css_lint"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "CSS Lint testing for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

